name: hungry
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_native_splash: ^2.0.5
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  camera: ^0.10.5+5
  gap: ^3.0.1
  external_path: ^1.0.3
  media_scanner: ^2.1.0
  carousel_slider: ^4.2.1
  http: ^0.13.6
  fl_chart: ^0.60.0
  lottie: ^2.2.0
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.3.0
  geolocator: ^11.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/BetterBitesLogo.png
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open sans/OpenSans-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#013220" # Background color of the splash screen
  image: assets/images/BetterBitesLogo.png # Path to your logo image in the assets folder
  android: true # Enable splash screen for Android
  ios: true # Enable splash screen for iOS
  android_scaleType: centerInside # Adjust the logo scaling (optional, use centerCrop, centerInside, fitCenter, etc.)
  ios_content_mode: center # Adjust the logo scaling for iOS (optional, use center, aspectFill, aspectFit, etc.)
  android_12:
    image: assets/images/BetterBitesLogo.png
    color: "#013220"